-- MySQL Script generated by MySQL Workbench
-- Wed Dec  1 12:15:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spmdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spmdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spmdb` DEFAULT CHARACTER SET utf8 ;
USE `spmdb` ;

-- -----------------------------------------------------
-- Table `spmdb`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spmdb`.`teacher` (
  `tid` INT NOT NULL AUTO_INCREMENT,
  `accont` VARCHAR(20) NULL,
  `password` VARCHAR(20) NULL,
  PRIMARY KEY (`tid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spmdb`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spmdb`.`room` (
  `rid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  `type` VARCHAR(10) NULL,
  `seat` VARCHAR(50) NULL,
  PRIMARY KEY (`rid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spmdb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spmdb`.`student` (
  `sid` INT NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(20) NULL,
  `password` VARCHAR(20) NULL,
  `clas` VARCHAR(10) NULL,
  PRIMARY KEY (`sid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spmdb`.`experiment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spmdb`.`experiment` (
  `eid` INT NOT NULL AUTO_INCREMENT,
  `tid` INT NOT NULL,
  `rid` INT NOT NULL,
  `name` VARCHAR(10) NULL,
  `subject` VARCHAR(10) NULL,
  `time` VARCHAR(20) NULL,
  `studyTime` INT NULL,
  `seat` VARCHAR(50) NULL,
  `isShared` TINYINT NULL,
  `phone` VARCHAR(15) NULL,
  PRIMARY KEY (`eid`),
  INDEX `fk_experiment_teacher_idx` (`tid` ASC) VISIBLE,
  INDEX `fk_experiment_room1_idx` (`rid` ASC) VISIBLE,
  CONSTRAINT `fk_experiment_teacher`
    FOREIGN KEY (`tid`)
    REFERENCES `spmdb`.`teacher` (`tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_experiment_room1`
    FOREIGN KEY (`rid`)
    REFERENCES `spmdb`.`room` (`rid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `spmdb`.`student_has_experiment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spmdb`.`student_has_experiment` (
  `student_sid` INT NOT NULL,
  `experiment_eid` INT NOT NULL,
  `seat` INT NULL,
  PRIMARY KEY (`student_sid`, `experiment_eid`),
  INDEX `fk_student_has_experiment_experiment1_idx` (`experiment_eid` ASC) VISIBLE,
  INDEX `fk_student_has_experiment_student1_idx` (`student_sid` ASC) VISIBLE,
  CONSTRAINT `fk_student_has_experiment_student1`
    FOREIGN KEY (`student_sid`)
    REFERENCES `spmdb`.`student` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_experiment_experiment1`
    FOREIGN KEY (`experiment_eid`)
    REFERENCES `spmdb`.`experiment` (`eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spmdb`.`administer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spmdb`.`administer` (
  `account` VARCHAR(20) NULL,
  `password` VARCHAR(20) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
